### PR TITLE
Serializing out link fields in rdf

### PR DESCRIPTION
**Pull request by dannylamb**
**GitHub Issue**: Part of this monstrosity https://github.com/Islandora-CLAW/islandora/pull/86

# What does this Pull Request do?

Serializes out link fields as uris.

# What's new?
A quick check to see if there's a 'uri' key in addition to 'value', and outputting the 'uri' value as an '@id'

# How should this be tested?

To be tested as part of https://github.com/Islandora-CLAW/islandora/pull/86

# Interested parties
@Islandora-CLAW/committers

### CODE REVIEW

**Comment by whikloj** [comment]
Once I get a chance to build this changed box I'm guessing it will make more sense. But for now I am assuming that due to the change in the direction of linking this is required? 

What happens without this?

**Comment by dannylamb** [comment]
@whikloj This is for taxonomy terms.  They have a link field for their external uris, and we want that in the jsonld.  Without it, in your triplestore, you'd know your object is tagged with /taxonomy/term/1, but not http://purl.org/dc/dcmitype/Collection.

**Comment by whikloj** [comment]
So this is what I am seeing in the triplestore.
```
<http://localhost:8000/node/1?_format=jsonld> | schema:additionalType | <http://localhost:8000/taxonomy/term/7?_format=jsonld>
```
Which is also what I am seeing in Fedora and therefore:
```
<http://localhost:8080/fcrepo/rest/65/9a/8a/6f/659a8a6f-a9f5-4536-bc35-126bfefb33ac> | schema:additionalType | <http://localhost:8000/taxonomy/term/7?_format=jsonld>
```

**Comment by whikloj** [comment]
So watching the code run I am guessing maybe this is not what I thought it was or should there be some new context alter to convert this internal term URI to the external URI?

**Comment by dannylamb** [comment]
@whikloj What you're seeing in Fedora is right, but you should see the additional triple for 

```<http://localhost:8000/node/1?_format=jsonld> | schema:additionalType | <http://purl.org/dc/dcmitype/Collection>```

due to inferencing.  Is there a owl:sameAs in the RDF for the taxonomy term?

**Comment by dannylamb** [comment]
@whikloj And yeah... it's not super straightforward.  It's sort of the path of least resistance to getting this info into the complete picture (e.g. resultant graph).

**Comment by whikloj** [comment]
Okay, so if I tag an object with the `Collection` term. Your code doesn't seem to get run at all and the resulting graph doesn't show the URI from the taxonomy term.
```
{
  "@graph": [
    {
      "@id": "http://localhost:8000/node/1?_format=jsonld",
      "@type": [
        "http://pcdm.org/models#Object"
      ],
      "http://purl.org/dc/terms/title": [
        {
          "@value": "This is a collection",
          "@language": "en"
        }
      ],
      "http://schema.org/author": [
        {
          "@id": "http://localhost:8000/user/1?_format=jsonld"
        }
      ],
      "http://schema.org/dateCreated": [
        {
          "@value": "2018-05-07T21:00:53+00:00",
          "@type": "http://www.w3.org/2001/XMLSchema#dateTime"
        }
      ],
      "http://schema.org/dateModified": [
        {
          "@value": "2018-05-07T21:01:31+00:00",
          "@type": "http://www.w3.org/2001/XMLSchema#dateTime"
        }
      ],
      "http://purl.org/dc/terms/description": [
        {
          "@value": "This is my first reversed collection",
          "@language": "en"
        }
      ],
      "http://schema.org/additionalType": [
        {
          "@id": "http://localhost:8000/taxonomy/term/7?_format=jsonld"
        }
      ]
    },
    {
      "@id": "http://localhost:8000/user/1?_format=jsonld",
      "@type": [
        "http://schema.org/Person"
      ]
    },
    {
      "@id": "http://localhost:8000/taxonomy/term/7?_format=jsonld",
      "@type": [
        "http://schema.org/Thing"
      ]
    }
  ]
}
```
I went to the "Collection" taxonomy term (term/7) and it does have a URI in it.
```
http://purl.org/dc/dcmitype/Collection
```

**Comment by whikloj** [comment]
Maybe we need an rdf mapping for the taxonomy terms?

**Comment by dannylamb** [comment]
@whikloj It's included in the islandora_feature module in https://github.com/Islandora-CLAW/islandora/pull/86

https://github.com/Islandora-CLAW/islandora/pull/86/files#diff-7d3ae0584b38911c500a2968dfd977a6

**Comment by whikloj** [comment]
@dannylamb ok, wait a minute. 
Is this the `url` for the taxonomy term?
```
"http://localhost:8000/taxonomy/term/7?_format=jsonld"
```

Because if I switch from `?_format=jsonld` to `?_format=json` that is what I see as the url.
```
"field_tags": [
  {
    "target_id": 8,
    "target_type": "taxonomy_term",
    "target_uuid":  "f00c8920-87b8-432a-a6bb-db842b26451d",
    "url": "/taxonomy/term/8"
  }
]
```

**Comment by whikloj** [comment]
For future reference, the `"http://localhost:8000/taxonomy/term/7?_format=jsonld"` is the correct output it is transformed to the alternate term via inference at the triplestore.

**Comment by dannylamb** [comment]
Thanks @whikloj

**Pull request merged**
