### PR TITLE
Move context controller from islandora to jsonld

### PR DESCRIPTION
**Pull request by whikloj**
**GitHub Issue**: https://github.com/Islandora-CLAW/CLAW/issues/802

## ~Do not merge until #25 has been merged.~

Related to: https://github.com/Islandora-CLAW/islandora/pull/80

# What does this Pull Request do?

* Adds the JsonldContextController and tests from Islandora.
* Changed the URL from `/context/{entity_type}/{bundle}` to `/jsonld/context/{entity_type}/{bundle}` as there is a lot of `context` in Drupal 😄 
* Changes the WebTestBase into a BrowserTestBase.
* Modified the test to verify the output context is correct.

No functional changes, and we don't currently use this code anywhere.

# What's new?

* Does this change require documentation to be updated? no
* Does this change add any new dependencies? no
* Does this change require any other modifications to be made to the repository
(ie. Regeneration activity, etc.)? no
* Could this change impact execution of existing code? no

# How should this be tested?

Tests should pass.

You can access a page at `http://localhost:8000/jsonld/context/node/islandora_image` that contains JSON of the `@context`

# Interested parties
@Islandora-CLAW/committers

### CODE REVIEW

**Comment by DiegoPino** [comment]
@whikloj I will never be able to fix conflicts on 808 if pulls keep coming. Please 🙏 let me know when you are done making changes and those are merged to continue. I'm just not that fast and have to much on my plate, thanks ☺️

**Comment by whikloj** [comment]
@DiegoPino this is unrelated as this is a functional test and issue-808 is all kernel tests so this PR and issue-808 should slide in together with no problems 👍

**Comment by whikloj** [comment]
@DiegoPino also as this code is not being used yet, it can wait until after your PR is merged just so you won't have any issues.

**Comment by whikloj** [comment]
@DiegoPino there is **always** more

**Pull request merged**
